version: "3.9"
   
services:
  db:
    image: library/postgres:12
    volumes:
      - pfm-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  drf:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ALLOWED_CLIENT_HOSTS=${ALLOWED_CLIENT_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SPARROW_SMS_TOKEN=${SPARROW_SMS_TOKEN}
    depends_on:
      - db
      # - es
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/code/static
      - media:/code/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "8009:80"
    depends_on:
      - drf
  # es: 
  #   image: elasticsearch:7.17.3
  #   environment: 
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports: 
  #     - "6005:9200"


volumes:
  pfm-db:
  static: 
  media:



