# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pfm drf - prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to server
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST_IP }}
          username: ${{ secrets.PROD_HOST_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: cd /home/devloops/pfm/drf && git pull && cd .. && docker compose exec  drf python manage.py migrate && docker compose exec drf python manage.py collectstatic --noinput && docker compose up -d --build drf
